FSMOCAMLOBJS = \
   lwt/lwt.cmo lwt/pqueue.cmo lwt/generic/lwt_unix_impl.cmo lwt/lwt_unix.cmo \
   fsmonitor/watchercommon.cmo ubase/safelist.cmo $(FSMDIR)/watcher.cmo

FSMCOBJS = $(FSMDIR)/fen_stubs.o
FSMOCAMLLIBS=unix.cma
